--------------------------------------------------------
--  File created - среда-июля-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "USER_TEST"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"FAM" VARCHAR2(100 BYTE), 
	"IMY" VARCHAR2(100 BYTE), 
	"OTCH" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "USER_TEST"."CLIENT" TO "GUEST";
  GRANT INSERT ON "USER_TEST"."CLIENT" TO "GUEST";
  GRANT SELECT ON "USER_TEST"."CLIENT" TO "GUEST";
  GRANT UPDATE ON "USER_TEST"."CLIENT" TO "GUEST";
--------------------------------------------------------
--  DDL for Table KARTOCHKI
--------------------------------------------------------

  CREATE TABLE "USER_TEST"."KARTOCHKI" 
   (	"ID_KART" NUMBER, 
	"NOMER_KART" NUMBER, 
	"CLIENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "USER_TEST"."KARTOCHKI" TO "GUEST";
  GRANT INSERT ON "USER_TEST"."KARTOCHKI" TO "GUEST";
  GRANT SELECT ON "USER_TEST"."KARTOCHKI" TO "GUEST";
  GRANT UPDATE ON "USER_TEST"."KARTOCHKI" TO "GUEST";
--------------------------------------------------------
--  DDL for Table VCLAD
--------------------------------------------------------

  CREATE TABLE "USER_TEST"."VCLAD" 
   (	"ID_VCD" NUMBER, 
	"NAME_VCLAD" VARCHAR2(100 BYTE), 
	"VID_VCLADA" VARCHAR2(100 BYTE), 
	"MONEY" NUMBER, 
	"ID_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "USER_TEST"."VCLAD" TO "GUEST";
  GRANT INSERT ON "USER_TEST"."VCLAD" TO "GUEST";
  GRANT SELECT ON "USER_TEST"."VCLAD" TO "GUEST";
  GRANT UPDATE ON "USER_TEST"."VCLAD" TO "GUEST";
REM INSERTING into USER_TEST.CLIENT
SET DEFINE OFF;
Insert into USER_TEST.CLIENT (ID_CLIENT,FAM,IMY,OTCH) values ('1','Копанько ','Гошка','Владимирович ');
Insert into USER_TEST.CLIENT (ID_CLIENT,FAM,IMY,OTCH) values ('2','Атаев','Миша','Игоревич');
Insert into USER_TEST.CLIENT (ID_CLIENT,FAM,IMY,OTCH) values ('3','Абросимов','Владислав','Андреевич');
Insert into USER_TEST.CLIENT (ID_CLIENT,FAM,IMY,OTCH) values ('4','Буц','Максим','Алексеевич');
REM INSERTING into USER_TEST.KARTOCHKI
SET DEFINE OFF;
Insert into USER_TEST.KARTOCHKI (ID_KART,NOMER_KART,CLIENT_ID) values ('1','123456789','4');
Insert into USER_TEST.KARTOCHKI (ID_KART,NOMER_KART,CLIENT_ID) values ('2','465475865','2');
Insert into USER_TEST.KARTOCHKI (ID_KART,NOMER_KART,CLIENT_ID) values ('3','436547743','3');
Insert into USER_TEST.KARTOCHKI (ID_KART,NOMER_KART,CLIENT_ID) values ('4','876846785','1');
REM INSERTING into USER_TEST.VCLAD
SET DEFINE OFF;
Insert into USER_TEST.VCLAD (ID_VCD,NAME_VCLAD,VID_VCLADA,MONEY,ID_CLIENT) values ('1','Открытие','Драг металлы','200','4');
Insert into USER_TEST.VCLAD (ID_VCD,NAME_VCLAD,VID_VCLADA,MONEY,ID_CLIENT) values ('2','ВТБ','Валюта','600','1');
Insert into USER_TEST.VCLAD (ID_VCD,NAME_VCLAD,VID_VCLADA,MONEY,ID_CLIENT) values ('3','Совкозсельхоз','Опцион','900','3');
Insert into USER_TEST.VCLAD (ID_VCD,NAME_VCLAD,VID_VCLADA,MONEY,ID_CLIENT) values ('4','Тинь','Рубли','1000','2');
--------------------------------------------------------
--  Constraints for Table KARTOCHKI
--------------------------------------------------------

  ALTER TABLE "USER_TEST"."KARTOCHKI" MODIFY ("ID_KART" NOT NULL ENABLE);
  ALTER TABLE "USER_TEST"."KARTOCHKI" ADD PRIMARY KEY ("ID_KART")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "USER_TEST"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "USER_TEST"."CLIENT" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VCLAD
--------------------------------------------------------

  ALTER TABLE "USER_TEST"."VCLAD" MODIFY ("ID_VCD" NOT NULL ENABLE);
  ALTER TABLE "USER_TEST"."VCLAD" ADD PRIMARY KEY ("ID_VCD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
