--------------------------------------------------------
--  File created - среда-июля-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VCLAD
--------------------------------------------------------

  CREATE TABLE "USER_TEST"."VCLAD" 
   (	"ID_VCD" NUMBER, 
	"NAME_VCLAD" VARCHAR2(100 BYTE), 
	"VID_VCLADA" VARCHAR2(100 BYTE), 
	"MONEY" NUMBER, 
	"ID_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "USER_TEST"."VCLAD" TO "GUEST";
  GRANT INSERT ON "USER_TEST"."VCLAD" TO "GUEST";
  GRANT SELECT ON "USER_TEST"."VCLAD" TO "GUEST";
  GRANT UPDATE ON "USER_TEST"."VCLAD" TO "GUEST";
--------------------------------------------------------
--  DDL for Index SYS_C007426
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_TEST"."SYS_C007426" ON "USER_TEST"."VCLAD" ("ID_VCD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VCLAD
--------------------------------------------------------

  ALTER TABLE "USER_TEST"."VCLAD" MODIFY ("ID_VCD" NOT NULL ENABLE);
  ALTER TABLE "USER_TEST"."VCLAD" ADD PRIMARY KEY ("ID_VCD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
