--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "USER_TEST"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"FAM" VARCHAR2(100 BYTE), 
	"IMY" VARCHAR2(100 BYTE), 
	"OTCH" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "USER_TEST"."CLIENT" TO "GUEST";
  GRANT INSERT ON "USER_TEST"."CLIENT" TO "GUEST";
  GRANT SELECT ON "USER_TEST"."CLIENT" TO "GUEST";
  GRANT UPDATE ON "USER_TEST"."CLIENT" TO "GUEST";
