--------------------------------------------------------
--  DDL for Table KARTOCHKI
--------------------------------------------------------

  CREATE TABLE "USER_TEST"."KARTOCHKI" 
   (	"ID_KART" NUMBER, 
	"NOMER_KART" NUMBER, 
	"CLIENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "USER_TEST"."KARTOCHKI" TO "GUEST";
  GRANT INSERT ON "USER_TEST"."KARTOCHKI" TO "GUEST";
  GRANT SELECT ON "USER_TEST"."KARTOCHKI" TO "GUEST";
  GRANT UPDATE ON "USER_TEST"."KARTOCHKI" TO "GUEST";
