--------------------------------------------------------
--  DDL for Table VCLAD
--------------------------------------------------------

  CREATE TABLE "USER_TEST"."VCLAD" 
   (	"ID_VCD" NUMBER, 
	"NAME_VCLAD" VARCHAR2(100 BYTE), 
	"VID_VCLADA" VARCHAR2(100 BYTE), 
	"MONEY" NUMBER, 
	"ID_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "USER_TEST"."VCLAD" TO "GUEST";
  GRANT INSERT ON "USER_TEST"."VCLAD" TO "GUEST";
  GRANT SELECT ON "USER_TEST"."VCLAD" TO "GUEST";
  GRANT UPDATE ON "USER_TEST"."VCLAD" TO "GUEST";
